{{- if .Values.egressgatewayAgent.prometheus.serviceMonitor.install -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.egressgatewayAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ default .Release.Namespace .Values.egressgatewayAgent.prometheus.serviceMonitor.namespace }}
  labels:
    {{- include "project.egressgatewayAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.egressgatewayAgent.prometheus.serviceMonitor.labels }}
    {{- include "tplvalues.render" ( dict "value" .Values.egressgatewayAgent.prometheus.serviceMonitor.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.egressgatewayAgent.prometheus.serviceMonitor.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.egressgatewayAgent.prometheus.serviceMonitor.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.egressgatewayAgent.prometheus.serviceMonitor.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "project.egressgatewayAgent.selectorLabels" . | nindent 6 }}
      {{- if .Values.global.commonLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
      {{- if .Values.egressgatewayAgent.podLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.egressgatewayAgent.podLabels "context" $ ) | nindent 6 }}
      {{- end }}
  {{- end }}
---
{{- if .Values.egressgatewayController.prometheus.serviceMonitor.install -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.egressgatewayController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ default .Release.Namespace .Values.egressgatewayController.prometheus.serviceMonitor.namespace }}
  labels:
    {{- include "project.egressgatewayController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.egressgatewayController.prometheus.serviceMonitor.labels }}
    {{- include "tplvalues.render" ( dict "value" .Values.egressgatewayController.prometheus.serviceMonitor.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.egressgatewayController.prometheus.serviceMonitor.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.egressgatewayController.prometheus.serviceMonitor.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.egressgatewayController.prometheus.serviceMonitor.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "project.egressgatewayController.selectorLabels" . | nindent 6 }}
      {{- if .Values.global.commonLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
      {{- if .Values.egressgatewayController.podLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.egressgatewayController.podLabels "context" $ ) | nindent 6 }}
      {{- end }}
{{- end }}
