name: 'Update Chart Readme'

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'charts/*/values.yaml'

permissions: write-all

jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v3
        with:
          repository: 'bitnami-labs/readme-generator-for-helm'
          ref: '1af12881436b1f58f0643d733fd5196b4a11caa8'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install readme-generator-for-helm dependencies
        run: |
          cd readme-generator-for-helm
          npm install

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: thisProject

      - name: Execute readme-generator-for-helm
        id: execute
        run: |
          # Using the Github API to detect the files changed as git merge-base stops working when the branch is behind
          # and jitterbit/get-changed-files does not support pull_request_target
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$URL")
          echo "files_changed_data: $files_changed_data"
          files_changed="$(echo $files_changed_data | jq -r '.[] | .filename')"
          echo "files_changed: $files_changed"
          # Adding || true to avoid "Process exited with code 1" errors
          charts_changed="$(echo "$files_changed" | grep -E -o "([^/]*)/values.yaml" | sort | uniq | awk -F'/' '{print $1}' | tr '\n' ' ' || true)"
          echo "charts_changed: $charts_changed"
          #--------------------
          for ITEM in $charts_changed ; do
            if [ -f "thisProject/charts/${ITEM}/values.yaml" ] && grep "charts/${ITEM}/values.yaml" <<< "$files_changed" &>/dev/null ; then
                echo "------ Updating README.md for ${ITEM}"
                readme-generator-for-helm/bin/index.js --values "thisProject/charts/${ITEM}/values.yaml" --readme "thisProject/charts/${ITEM}/README.md" --schema "/tmp/schema.json"
                cat thisProject/charts/${ITEM}/README.md
            fi
          done

      - name: Push changes
        run: |
          # Push all the changes
          cd thisProject
          if git status -s | grep README.md; then
            set -x
            echo "create pr"
            git branch
            git status
            git config --list
            git config user.name  "Robot"
            git config user.email "robot@spidernet-io.github.io"
            git add .
            git commit -am "Update README.md with readme-generator-for-helm" --signoff
            git push
          fi
